AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: function/.
      Description: Scrape the latest tweets from VaxHuntersCan twitter account and load into DB via API
      MemorySize: 400
      Timeout: 600
      Policies:
        - Statement:
            - Sid: AWSLambdaVPCAccessExecutionRole
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - ec2:CreateNetworkInterface
                - ec2:DescribeNetworkInterfaces
                - ec2:DeleteNetworkInterface
              Resource: '*'
            - Sid: AmazonElasticFileSystemClientFullAccess
              Effect: Allow
              Action:
                - elasticfilesystem:ClientMount
                - elasticfilesystem:ClientRootAccess
                - elasticfilesystem:ClientWrite
                - elasticfilesystem:DescribeMountTargets
              Resource: '*'
      Layers:
        - !Ref libs
        - !Ref numpypandas
        - !Ref sklearn
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: twitter-scraper-lib
      Description: Dependencies for the twitter-scraper sample app.
      ContentUri: package/.
      CompatibleRuntimes:
        - python3.8
  numpypandas:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: numpypandas
      Description: numpy and pandas.
      ContentUri: numpypandas/.
      CompatibleRuntimes:
        - python3.8
  sklearn:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sklearn
      Description: sklearn.
      ContentUri: sklearn/.
      CompatibleRuntimes:
        - python3.8
